version: '3.1'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /backup:/opt/backup
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Rosangela@123
      - MYSQL_DATABASE=factory
      - MYSQL_USER=factoryprojetos
      - MYSQL_PASSWORD=Factory@1207
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    environment:
      - ADMINER_DESIGN=pepa-linha
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
